menu:
 Archive: /archives
 Tags: /tags
 RSS: /atom.xml

widgets:
 - site_links
 - greeting

rss: /atom.xml

readMore: ...read more

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
